lib: [
  "_build/install/default/lib/MiniKanren/META"
  "_build/install/default/lib/MiniKanren/MiniKanren.a"
  "_build/install/default/lib/MiniKanren/MiniKanren.cma"
  "_build/install/default/lib/MiniKanren/MiniKanren.cmxa"
  "_build/install/default/lib/MiniKanren/MiniKanren.ml"
  "_build/install/default/lib/MiniKanren/MiniKanren.mli"
  "_build/install/default/lib/MiniKanren/MiniKanrenStd.ml"
  "_build/install/default/lib/MiniKanren/MiniKanrenStd.mli"
  "_build/install/default/lib/MiniKanren/Tester/tester.a" {"Tester/tester.a"}
  "_build/install/default/lib/MiniKanren/Tester/tester.cma" {"Tester/tester.cma"}
  "_build/install/default/lib/MiniKanren/Tester/tester.cmi" {"Tester/tester.cmi"}
  "_build/install/default/lib/MiniKanren/Tester/tester.cmt" {"Tester/tester.cmt"}
  "_build/install/default/lib/MiniKanren/Tester/tester.cmx" {"Tester/tester.cmx"}
  "_build/install/default/lib/MiniKanren/Tester/tester.cmxa" {"Tester/tester.cmxa"}
  "_build/install/default/lib/MiniKanren/Tester/tester.ml" {"Tester/tester.ml"}
  "_build/install/default/lib/MiniKanren/dune-package"
  "_build/install/default/lib/MiniKanren/miniKanren.cmi"
  "_build/install/default/lib/MiniKanren/miniKanren.cmt"
  "_build/install/default/lib/MiniKanren/miniKanren.cmti"
  "_build/install/default/lib/MiniKanren/miniKanren.cmx"
  "_build/install/default/lib/MiniKanren/miniKanrenStd.cmi"
  "_build/install/default/lib/MiniKanren/miniKanrenStd.cmt"
  "_build/install/default/lib/MiniKanren/miniKanrenStd.cmti"
  "_build/install/default/lib/MiniKanren/miniKanrenStd.cmx"
  "_build/install/default/lib/MiniKanren/opam"
  "_build/install/default/lib/MiniKanren/syntax/pa_minikanren.ml" {"syntax/pa_minikanren.ml"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.a" {"syntax/pa_ocanren.a"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cma" {"syntax/pa_ocanren.cma"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cmi" {"syntax/pa_ocanren.cmi"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cmt" {"syntax/pa_ocanren.cmt"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cmx" {"syntax/pa_ocanren.cmx"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cmxa" {"syntax/pa_ocanren.cmxa"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.ml" {"syntax/pa_ocanren.ml"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren__Pa_minikanren.cmi" {"syntax/pa_ocanren__Pa_minikanren.cmi"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren__Pa_minikanren.cmt" {"syntax/pa_ocanren__Pa_minikanren.cmt"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren__Pa_minikanren.cmx" {"syntax/pa_ocanren__Pa_minikanren.cmx"}
]
libexec: [
  "_build/install/default/lib/MiniKanren/MiniKanren.cmxs"
  "_build/install/default/lib/MiniKanren/Tester/tester.cmxs" {"Tester/tester.cmxs"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cmxs" {"syntax/pa_ocanren.cmxs"}
]
doc: [
  "_build/install/default/doc/MiniKanren/README.md"
]
