lib: [
  "_build/install/default/lib/MiniKanren/META"
  "_build/install/default/lib/MiniKanren/Tester/tester.a" {"Tester/tester.a"}
  "_build/install/default/lib/MiniKanren/Tester/tester.cma" {"Tester/tester.cma"}
  "_build/install/default/lib/MiniKanren/Tester/tester.cmi" {"Tester/tester.cmi"}
  "_build/install/default/lib/MiniKanren/Tester/tester.cmt" {"Tester/tester.cmt"}
  "_build/install/default/lib/MiniKanren/Tester/tester.cmx" {"Tester/tester.cmx"}
  "_build/install/default/lib/MiniKanren/Tester/tester.cmxa" {"Tester/tester.cmxa"}
  "_build/install/default/lib/MiniKanren/Tester/tester.ml" {"Tester/tester.ml"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/.public_cmi/miniKanren.cmi" {"__private__/MiniKanren/.public_cmi/miniKanren.cmi"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/.public_cmi/miniKanren.cmt" {"__private__/MiniKanren/.public_cmi/miniKanren.cmt"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/.public_cmi/miniKanren.cmti" {"__private__/MiniKanren/.public_cmi/miniKanren.cmti"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/.public_cmi/miniKanrenStd.cmi" {"__private__/MiniKanren/.public_cmi/miniKanrenStd.cmi"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/.public_cmi/miniKanrenStd.cmt" {"__private__/MiniKanren/.public_cmi/miniKanrenStd.cmt"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/.public_cmi/miniKanrenStd.cmti" {"__private__/MiniKanren/.public_cmi/miniKanrenStd.cmti"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/MiniKanren.a" {"__private__/MiniKanren/MiniKanren.a"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/MiniKanren.cma" {"__private__/MiniKanren/MiniKanren.cma"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/MiniKanren.cmxa" {"__private__/MiniKanren/MiniKanren.cmxa"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/MiniKanren.ml" {"__private__/MiniKanren/MiniKanren.ml"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/MiniKanren.mli" {"__private__/MiniKanren/MiniKanren.mli"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/MiniKanrenStd.ml" {"__private__/MiniKanren/MiniKanrenStd.ml"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/MiniKanrenStd.mli" {"__private__/MiniKanren/MiniKanrenStd.mli"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/miniKanren.cmx" {"__private__/MiniKanren/miniKanren.cmx"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/miniKanrenStd.cmx" {"__private__/MiniKanren/miniKanrenStd.cmx"}
  "_build/install/default/lib/MiniKanren/dune-package"
  "_build/install/default/lib/MiniKanren/opam"
  "_build/install/default/lib/MiniKanren/syntax/pa_minikanren.ml" {"syntax/pa_minikanren.ml"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.a" {"syntax/pa_ocanren.a"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cma" {"syntax/pa_ocanren.cma"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cmi" {"syntax/pa_ocanren.cmi"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cmt" {"syntax/pa_ocanren.cmt"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cmx" {"syntax/pa_ocanren.cmx"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cmxa" {"syntax/pa_ocanren.cmxa"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.ml" {"syntax/pa_ocanren.ml"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren__Pa_minikanren.cmi" {"syntax/pa_ocanren__Pa_minikanren.cmi"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren__Pa_minikanren.cmt" {"syntax/pa_ocanren__Pa_minikanren.cmt"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren__Pa_minikanren.cmx" {"syntax/pa_ocanren__Pa_minikanren.cmx"}
]
libexec: [
  "_build/install/default/lib/MiniKanren/Tester/tester.cmxs" {"Tester/tester.cmxs"}
  "_build/install/default/lib/MiniKanren/__private__/MiniKanren/MiniKanren.cmxs" {"__private__/MiniKanren/MiniKanren.cmxs"}
  "_build/install/default/lib/MiniKanren/syntax/pa_ocanren.cmxs" {"syntax/pa_ocanren.cmxs"}
]
doc: [
  "_build/install/default/doc/MiniKanren/README.md"
]
