(executables
 (names tree sorting WGC)
 (modules tree sorting WGC)
 (libraries GT OCanren)
 (preprocess
  (action
   (run
    %{project_root}/camlp5/pp5+gt+plugins+ocanren+logger+dump.exe
    %{input-file})))
 (preprocessor_deps
  (file %{project_root}/camlp5/pp5+gt+plugins+ocanren+logger+dump.exe)))

(executable
 (name len)
 (modules len)
 (libraries GT OCanren benchmark)
 (preprocess
  (action
   (run
    %{project_root}/camlp5/pp5+gt+plugins+ocanren+logger+dump.exe
    %{input-file})))
 (preprocessor_deps
  (file %{project_root}/camlp5/pp5+gt+plugins+ocanren+logger+dump.exe)))

(executable
 (name hack)
 (modules hack)
 (libraries GT OCanren)
 (ocamlc_flags
  (:standard -dsource))
 (preprocess
  (action
   (run
    %{project_root}/ppx/pp_distrib_gt.exe
    -pp
    %{project_root}/camlp5/pp5+ocanren+dump.exe
    %{input-file})))
 (preprocessor_deps
  (file %{project_root}/ppx/pp_distrib_gt.exe)
  (file %{project_root}/camlp5/pp5+ocanren+dump.exe)
  (file %{project_root}/camlp5/pp5+ocanren+o.exe)))

(alias
 (name samples)
 (deps tree.exe sorting.exe WGC.exe lorry.exe len.exe))
