(* SPDX-License-Identifier: LGPL-2.1-or-later *)
(*
 * OCanren.
 * Copyright (C) 2015-2022
 * Dmitri Boulytchev, Dmitry Kosarev, Alexey Syomin, Evgeny Moiseenko
 * St.Petersburg State University, JetBrains Research
 *
 * This software is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License version 2, as published by the Free Software Foundation.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the GNU Library General Public License version 2 for more details
 * (enclosed in the file COPYING).
 *)

open Stdlib

(** {3 Logic values} *)

(** A type of a logic value *)
@type 'a logic =
| Var   of GT.int * 'a logic GT.list
| Value of 'a with show, gmap, html, eq, compare, foldl, foldr, fmt

(** [to_logic x] makes a logic value from a regular one *)
val to_logic : 'a -> 'a logic

(** [from_logic x] makes a regular value from a logic one.
    Raises exception [Not_a_value] if [x] contains free variables
*)
val from_logic : 'a logic -> 'a

(** {3 Injections/projections} *)

(** The type ['a ilogic] describes an injection of a type ['a] into logical domain.
    For example, injection of type [int list] will be [int ilogic list ilogic].
    The conversions from ['a ilogic] to ['a] is performed via {i reifiers}.

    @canonical OCanren.ilogic *)
type ('a, 'b) injected

module Reifier : sig
  (** Reifier from type ['a] into type ['b] is an ['a -> 'b] function
     dipped into the {!Env.t} monad. We will see how it plays later.

     Perhaps, it is possible to not expose the reifier type and make it itself
     a monad or something else that composes nicely, but we haven't figured out yet.
    *)

  (** @canonical OCanren.Reifier.t *)
  type ('a, 'b) t = ('a -> 'b) Env.Monad.t

  (** A few predefined reifiers from which other reifiers will be composed *)

  (* this one transforms implicit logic value into regular logic value. *)
  val reify : ( 'a, 'a logic) t

  (** This one projects implicit logic into the underlying type,
    raising exception {!Not_a_value} if it finds a variable.
  *)
  val prj_exn : ('a, 'a) t

  val prj : (int -> 'a) -> ('a, 'a) t


  (* Interesting part --- we can apply a reifier to a value dipped into `State.t` comonad *)
  (* val apply : ('a, 'b) t -> 'a State.t -> 'b *)

  (** Composition of two reifiers. *)
  val compose : ('a, 'b) t -> ('b, 'c) t -> ('a, 'c) t

  (** Reifier is a profunctor. Below are two combinators
    to compose reifiers with regular functions
   *)

  val fmap : ('b -> 'c) -> ('a, 'b) t -> ('a, 'c) t

  val fcomap : ('a -> 'b) -> ('b, 'c) t -> ('a, 'c) t

  (** Fixpoint for reifier. *)
  val fix: ( ('a, 'b) t as 'c -> 'c) -> 'c

  (** And uxiliary function to make reifiers generated by generic programming point-free. *)
  val rework : fv:('a Env.m -> 'b Env.m)
      -> ('a logic Env.m -> 'b logic Env.m)
      -> 'a logic Env.m
      -> 'b logic Env.m

  (** Fix point combinator for Call-by-value *)
  val zed: (('a -> 'b) -> 'a -> 'b) -> 'a -> 'b
end

val lift : 'a -> ('a, 'a) injected

(** [inj x] injects [x] into logical [x]. *)
val inj : ('a, 'b) injected -> ('a, 'b logic) injected

(** A synonym for {!inj} (for non-parametric types). *)
val (!!) :  ('a, 'b) injected -> ('a, 'b logic) injected

(** [prj_exn x] returns a regular value from injected representation.
    Raises exception [Not_a_value] if [x] contains free variables
 *)
val prj_exn : ('a, 'a) Reifier.t

(* val prj : (int -> 'a) -> ('a ilogic, 'a) Reifier.t *)

(** A default shallow reifier. An alias of {!Reifier.reify}. *)
val reify : ('a, 'a logic) Reifier.t

(** The exception is raised when we try to extract a regular term from the answer with some free variables. *)
exception Not_a_value

(** Reification result.

    @canonical OCanren.reified *)
class type ['a, 'b] reified =
object
  (** Returns [true] if the term has any free logic variable inside. *)
  method is_open: bool

  (** Gets the answer as a logic value using provided reifier. *)
  method reify: 'b . ('a, 'b) Reifier.t -> 'b
end

val make_rr : Env.t -> ('a, 'b) injected -> ('a, 'b) reified


(** {2 Building reifiers compositionally } *)
module type T0 =
  sig
    type t
    val fmap : t -> t
  end
module type T1 =
  sig
    type 'a t
    val fmap : ('a -> 'b) -> 'a t -> 'b t
  end

module type T2 =
  sig
   type ('a, 'b) t
   val fmap : ('a -> 'c) -> ('b -> 'd) -> ('a, 'b) t -> ('c, 'd) t
  end

module type T3 =
  sig
    type ('a, 'b, 'c) t
    val fmap : ('a -> 'q) -> ('b -> 'r) -> ('c -> 's) -> ('a, 'b, 'c) t -> ('q, 'r, 's) t
  end

module type T4 =
sig
  type ('a, 'b, 'c, 'd) t
  val fmap : ('a -> 'q) -> ('b -> 'r) -> ('c -> 's) -> ('d -> 't) -> ('a, 'b, 'c, 'd) t -> ('q, 'r, 's, 't) t
end

module type T5 =
sig
  type ('a, 'b, 'c, 'd, 'e) t
  val fmap : ('a -> 'q) -> ('b -> 'r) -> ('c -> 's) -> ('d -> 't) -> ('e -> 'u) -> ('a, 'b, 'c, 'd, 'e) t -> ('q, 'r, 's, 't, 'u) t
end

module type T6 =
sig
  type ('a, 'b, 'c, 'd, 'e, 'f) t
  val fmap : ('a -> 'q) -> ('b -> 'r) -> ('c -> 's) -> ('d -> 't) -> ('e -> 'u) -> ('f -> 'v) -> ('a, 'b, 'c, 'd, 'e, 'f) t -> ('q, 'r, 's, 't, 'u, 'v) t
end

module Fmap1 :  functor (T : T1) -> sig
  external distrib : ('a, 'b) injected T.t -> ('a T.t, 'b T.t) injected = "%identity"

  val reify :
    ('a, 'b) Reifier.t -> ('a T.t, 'b T.t logic) Reifier.t
  val prj_exn :
  ('a, 'b) Reifier.t -> ('a T.t, 'b T.t) Reifier.t
end

module Fmap2 (T : T2) : sig
  external distrib : (('a,'c) injected, ('b,'d) injected) T.t -> (('a, 'b) T.t, ('c, 'd) T.t) injected = "%identity"
  val reify : ('a, 'b) Reifier.t -> ('c, 'd) Reifier.t -> (('a, 'c) T.t, ('b, 'd) T.t logic) Reifier.t
  val prj_exn: ('a, 'c) Reifier.t -> ('b, 'd) Reifier.t -> (('a, 'b) T.t, ('c, 'd) T.t) Reifier.t
end