(include_subdirs unqualified)

(library
 (name OCanren)
 (public_name OCanren)
 (libraries GT mtime.clock.os streaming z3)
 (flags
  (:standard -short-paths -rectypes))
 (inline_tests)
 (modules_without_implementation DISEQ_SIG CORE_SIG)
 (preprocess
  (per_module
   ((pps ppx_expect ppx_inline_test GT.ppx_all ppx_optcomp)
    Disequality
    Disequality2
    DISEQ_SIG
    ; CORE_SIG
    Term
    FM
    ;Tabling
    ;
    Pair
    Option
    Nat
    Listo
    Bool
    Subst
    Stream
    Peep
    Logic
    Core)
   ;  )
   ;  ((action
   ;    (run %{project_root}/camlp5/pp5+gt+plugins+dump.exe %{input-file}))
   ;   Pair
   ;   Option
   ;   Nat
   ;   Listo
   ;   Bool
   ;   Subst
   ;   Stream
   ;   Peep
   ;   Logic
   ;   Core)
   )))
