(library
 (name MiniKanren)
 ;(package MiniKanren)
 (public_name MiniKanren)
 (modules MiniKanren MiniKanrenStd MKStream MKStream_sig)
 (modules_without_implementation MKStream_sig)
 (wrapped false)
 (libraries GT)
 (flags
  (:standard -rectypes))
 (preprocess
  (action
   (run %{project_root}/camlp5/pp5+gt+plugins+dump.exe %{input-file}))))
