(env
 (dev
  (flags
   (:standard -w -27))))

(include_subdirs unqualified)

(library
 (name OCanren)
 (public_name OCanren)
 (modules
  Logic
  Core
  Stream
  Subst
  Term
  Env
  Runconf
  Disequality
  Option
  Bool
  Nat
  Pair
  Triple
  List
  Timer
  Peep
  OCanren)
 (libraries GT)
 (flags
  (:standard -rectypes -short-paths))
 (preprocessor_deps optcomp-cookie.cfg)
 (preprocess
  (pps
   GT.ppx_all
   ppx_optcomp
   --
   ;  -cookie
   ;  %{read-lines:./optcomp-cookie.cfg}
   )))

(documentation
 (package OCanren)
 (mld_files index))
